name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install
      - run: npm run build
      - run: npm test -- --coverageReporters=text-lcov | npx coveralls
